let handler = async (m, { conn, usedPrefix: _p, __dirname, args }) => {
let url = 'https://telegra.ph/file/6ab4daac226292a112540.jpg'
let text = `*MENUレゼ.LISTレゼ.REZBOTレゼ.*
===============
レゼ.absen_absen
レゼ.absen_cekabsen
レゼ.absen_delete
レゼ.absen_start
レゼ.accbang
レゼ.afk-_afk
レゼ.afk-afk
レゼ.alkitab
レゼ.all-soundmenu
レゼ.animalfact
レゼ.anime-anna
レゼ.anime-asuna
レゼ.anime-chara-gi
レゼ.anime-charainfo
レゼ.anime-chitoge
レゼ.anime-cosplay
レゼ.anime-elaina
レゼ.anime-emilia
レゼ.anime-film
レゼ.anime-gremory
レゼ.anime-info
レゼ.anime-jahy
レゼ.anime-kaguya
レゼ.anime-kaneki
レゼ.anime-kanna
レゼ.anime-kanna1
レゼ.anime-kotori
レゼ.anime-kurumi
レゼ.anime-kusonime
レゼ.anime-link
レゼ.anime-loli
レゼ.anime-lolice
レゼ.anime-mangainfo
レゼ.anime-mikasa
レゼ.anime-neko
レゼ.anime-nezuko
レゼ.anime-otakudesu
レゼ.anime-paijo
レゼ.anime-random
レゼ.anime-randomanime
レゼ.anime-rize
レゼ.anime-sagiri
レゼ.anime-shina
レゼ.anime-shota
レゼ.anime-simpown
レゼ.anime-waifu
レゼ.anime-yotsuba
レゼ.anime-yuki
レゼ.anime_husbu
レゼ.anonymous-sendkontak
レゼ.anonymous_chat
レゼ.anonymous_chat_.js
レゼ.anticulik
レゼ.antitoxic
レゼ.antiviewonce
レゼ.asmaulhusna
レゼ.asupan
レゼ.asupan2
レゼ.audio-anime
レゼ.audio-cut
レゼ.audio-dj1
レゼ.audio-dj2
レゼ.audio-effect
レゼ.audio-tomp3
レゼ.audio-toptt
レゼ.autobio
レゼ.autosticker
レゼ.balas-grup
レゼ.balas
レゼ.bank-cek
レゼ.bank-nabung
レゼ.bank-tarik
レゼ.benarkah
レゼ.bkp
レゼ.bokep
レゼ.botレゼ.off
レゼ.botレゼ.on
レゼ.bot-on-off
レゼ.broadcast
レゼ.broadcastchats
レゼ.broadcastgroups
レゼ.carapakai
レゼ.cecan
レゼ.cek-warn
レゼ.cerpen
レゼ.cmd-del
レゼ.cmd-list
レゼ.cmd-lock
レゼ.cmd-set
レゼ.cogan
レゼ.complaint
レゼ.creator
レゼ.donasi
レゼ.downloader-facebook
レゼ.downloader-gdrive
レゼ.downloader-gitclone
レゼ.downloader-ig
レゼ.downloader-igstalk
レゼ.downloader-mediafire
レゼ.downloader-pptiktok
レゼ.downloader-telesticker
レゼ.downloader-tiktok
レゼ.downloader-ttaudio
レゼ.downloader-twiter
レゼ.downloader-xnxxsearch
レゼ.downloader-zippyshare
レゼ.emojimix
レゼ.enable
レゼ.exp-ceksn
レゼ.exp-daftar
レゼ.exp-guest
レゼ.exp-my
レゼ.exp-sn
レゼ.exp-tomoney
レゼ.exp-unreg
レゼ.expired-cek
レゼ.expired-del
レゼ.expired-set
レゼ.fkon
レゼ.fun-angka
レゼ.fun-apakah
レゼ.fun-apakah2
レゼ.fun-artikata
レゼ.fun-artimimpi
レゼ.fun-artinama
レゼ.fun-bisakah
レゼ.fun-cantikcek
レゼ.fun-ceksifat
レゼ.fun-dadu
レゼ.fun-dimanakah
レゼ.fun-gantengcek
レゼ.fun-generate_nama
レゼ.fun-generate_purba
レゼ.fun-how
レゼ.fun-jadian
レゼ.fun-kapankah
レゼ.fun-kapankah2
レゼ.fun-kerangajaib
レゼ.fun-masadepan
レゼ.fun-morse
レゼ.fun-pat
レゼ.fun-simi
レゼ.fun-susunkata
レゼ.fun-susunkata_ans
レゼ.fun-susunkata_hint
レゼ.fun-tahugasih
レゼ.fun-tololcek
レゼ.fun-top
レゼ.fun-wibucek
レゼ.game-caklontong
レゼ.game-caklontong_ans
レゼ.game-caklontong_hint
レゼ.game-family100
レゼ.game-family100_answer
レゼ.game-iqtest
レゼ.game-lengkapikalimat-ans
レゼ.game-lengkapikalimat-hint
レゼ.game-lengkapikalimat
レゼ.game-math
レゼ.game-math_answer
レゼ.game-siapakahaku
レゼ.game-siapakahaku_ans
レゼ.game-siapakahaku_hint
レゼ.game-tebakbendera-ans
レゼ.game-tebakbendera-hint
レゼ.game-tebakbendera
レゼ.game-tebakgame-ans
レゼ.game-tebakgame-hint
レゼ.game-tebakgame
レゼ.game-tebakjenaka-ans
レゼ.game-tebakjenaka-hint
レゼ.game-tebakjenaka
レゼ.game-tebakkabupaten-ans
レゼ.game-tebakkabupaten-hint
レゼ.game-tebakkabupaten
レゼ.game-tebakkalimat-ans
レゼ.game-tebakkalimat-hint
レゼ.game-tebakkalimat
レゼ.game-tebaksiapa-ans
レゼ.game-tebaksiapa-hint
レゼ.game-tebaksiapa
レゼ.game-tebakumur
レゼ.games-_tictactoe
レゼ.games-tebakkata
レゼ.games-tebakkata_ans
レゼ.games-tebakkata_hint
レゼ.games-tictactoe
レゼ.google
レゼ.group-add
レゼ.group-demote
レゼ.group-getbio
レゼ.group-info
レゼ.group-intro
レゼ.group-kick
レゼ.group-link
レゼ.group-pengumuman
レゼ.group-promote
レゼ.group-setbye
レゼ.group-setdesc
レゼ.group-setnamegc
レゼ.group-setpp
レゼ.group-settings
レゼ.group-setwelcome
レゼ.group-spam
レゼ.group-tagall
レゼ.group-tagme
レゼ.group-teruskan
レゼ.group-time
レゼ.group-titlein
レゼ.groupbot
レゼ.grouptime
レゼ.host-bcgcb
レゼ.image-gimage
レゼ.image-meme
レゼ.image-pinterest
レゼ.image-wallpaper
レゼ.img-kitmeme
レゼ.indohot
レゼ.info-bannedlist
レゼ.info-boost
レゼ.info-botinfo
レゼ.info-dashboard
レゼ.info-database
レゼ.info-gcbot
レゼ.info-listpc
レゼ.info-report
レゼ.info-report_ans
レゼ.info-request
レゼ.info-rules
レゼ.info-runtime
レゼ.info-script
レゼ.info-sistembot
レゼ.info-speedtest
レゼ.info-statserver
レゼ.info-totalfitur
レゼ.info-versibot
レゼ.internet-charagi
レゼ.internet-covid
レゼ.internet-darkjokes
レゼ.internet-fetch
レゼ.internet-ghsearch
レゼ.internet-jadwalbola
レゼ.internet-kbbi
レゼ.internet-kuncigitar
レゼ.internet-messi
レゼ.internet-nomorhoki
レゼ.internet-ppcp
レゼ.internet-ronaldo
レゼ.internet-ssweb
レゼ.islam-asmaulhusna
レゼ.islam-ayatkursi
レゼ.islam-bacaansholat
レゼ.islam-hadis
レゼ.islam-jadwalsholat
レゼ.islam-kisahnabi
レゼ.islam-murothal
レゼ.islam-sallam
レゼ.jadian-cek
レゼ.jadian-iklhas
レゼ.jadian-nembak
レゼ.jadian-putus
レゼ.jadian-terima
レゼ.jadian-tolak
レゼ.join
レゼ.kristian-alkitab
レゼ.levelup
レゼ.limit
レゼ.lyrics
レゼ.main-menu
レゼ.maker-blackpink
レゼ.maker-bonk
レゼ.maker-carbon
レゼ.maker-donaltrump
レゼ.maker-gta
レゼ.maker-hornycard
レゼ.maker-itssostupid
レゼ.maker-lisapresent
レゼ.maker-logokaneki
レゼ.maker-logoneko
レゼ.maker-logosadboy
レゼ.maker-loli
レゼ.maker-pfun
レゼ.maker-photofilter
レゼ.maker-photomaker
レゼ.maker-pilihan
レゼ.maker-randem
レゼ.maker-randem2
レゼ.maker-rem
レゼ.maker-simpcard
レゼ.maker-tahtacostum
レゼ.maker-text1
レゼ.maker-text2
レゼ.maker-text3
レゼ.maker-ytcomment
レゼ.maker_glass
レゼ.menfess
レゼ.menu-awal
レゼ.mode-bot
レゼ.nsfw-nhentai
レゼ.nsfw-rule34
レゼ.nulis-googglesugest
レゼ.nulis-hartatahta.
レゼ.nulis-nulis
レゼ.nulis-nulis2
レゼ.openai
レゼ.owner-add
レゼ.owner-addowner
レゼ.owner-addprem
レゼ.owner-backup
レゼ.owner-banchat
レゼ.owner-banuser
レゼ.owner-botoff
レゼ.owner-boton
レゼ.owner-cheatlimit
レゼ.owner-cleartmp
レゼ.owner-creategroup
レゼ.owner-delowner
レゼ.owner-delprem
レゼ.owner-deluser
レゼ.owner-demote
レゼ.owner-df
レゼ.owner-emailpesan
レゼ.owner-exec
レゼ.owner-exec2
レゼ.owner-fituroff
レゼ.owner-fituron
レゼ.owner-fix
レゼ.owner-fun-off
レゼ.owner-fun-on
レゼ.owner-gcemail
レゼ.owner-getconfig
レゼ.owner-getdb
レゼ.owner-getfile
レゼ.owner-getname
レゼ.owner-getsessi
レゼ.owner-gp
レゼ.owner-grouplist
レゼ.owner-join
レゼ.owner-kick
レゼ.owner-leavegc
レゼ.owner-listprem
レゼ.owner-nilai
レゼ.owner-nowa
レゼ.owner-order
レゼ.owner-promote
レゼ.owner-resetlimit
レゼ.owner-resetprefix
レゼ.owner-resetuser
レゼ.owner-restart
レゼ.owner-rf
レゼ.owner-setbotbio
レゼ.owner-setmenu
レゼ.owner-setppanjang
レゼ.owner-setppbot
レゼ.owner-setwelcome
レゼ.owner-sf
レゼ.owner-simulate
レゼ.owner-tesbot
レゼ.owner-unbanchat
レゼ.owner-unbanuser
レゼ.owner_bug
レゼ.owner_setppanjang
レゼ.owner_warvirtex
レゼ.pantun
レゼ.payment
レゼ.pornhub
レゼ.prem-nsfw
レゼ.premium-creategc
レゼ.preset1
レゼ.preset10
レゼ.preset2
レゼ.preset3
レゼ.preset4
レゼ.preset5
レゼ.preset6
レゼ.preset7
レゼ.preset8
レゼ.preset9
レゼ.quote-motivasi
レゼ.quotes-anime
レゼ.quotes-bacot
レゼ.quotes-bucin
レゼ.quotes-dare
レゼ.quotes-galau
レゼ.quotes-gombal
レゼ.quotes-hacker
レゼ.quotes-katabijak
レゼ.quotes-truth
レゼ.random-sfx
レゼ.random-sound
レゼ.rate
レゼ.repeat
レゼ.resetlimit
レゼ.rpg-adventure
レゼ.rpg-antipmo
レゼ.rpg-atmmins
レゼ.rpg-atmplus
レゼ.rpg-berburu
レゼ.rpg-berdagang
レゼ.rpg-berkebon
レゼ.rpg-bet
レゼ.rpg-bonus
レゼ.rpg-bunuh
レゼ.rpg-buylimit
レゼ.rpg-casino
レゼ.rpg-cheat
レゼ.rpg-collect
レゼ.rpg-craft
レゼ.rpg-daily
レゼ.rpg-duel
レゼ.rpg-dungeon
レゼ.rpg-feed
レゼ.rpg-fighting
レゼ.rpg-freegift
レゼ.rpg-gajian
レゼ.rpg-heal
レゼ.rpg-hour
レゼ.rpg-hunt
レゼ.rpg-inventory
レゼ.rpg-kandang
レゼ.rpg-karung
レゼ.rpg-kerja
レゼ.rpg-koboy
レゼ.rpg-kolam
レゼ.rpg-leaderboard
レゼ.rpg-maling
レゼ.rpg-mancing
レゼ.rpg-membunuh
レゼ.rpg-merampok
レゼ.rpg-mining
レゼ.rpg-misi
レゼ.rpg-monthly
レゼ.rpg-mulung
レゼ.rpg-nebang
レゼ.rpg-ngentud
レゼ.rpg-nguli
レゼ.rpg-ojek
レゼ.rpg-open
レゼ.rpg-pasar
レゼ.rpg-petstore
レゼ.rpg-polisi
レゼ.rpg-premgift
レゼ.rpg-profile
レゼ.rpg-referal
レゼ.rpg-repair
レゼ.rpg-role
レゼ.rpg-sampah
レゼ.rpg-selectkil
レゼ.rpg-shop
レゼ.rpg-slot
レゼ.rpg-taxy
レゼ.rpg-transfer
レゼ.rpg-upgrade
レゼ.rpg-war
レゼ.rpg-warzone
レゼ.rpg-weekly
レゼ.ryhar-ttmp3
レゼ.search-joox
レゼ.self
レゼ.setbotpp
レゼ.setname_gc
レゼ.setppbot
レゼ.setpppanjang
レゼ.sewabot
レゼ.sewabot2
レゼ.shortlink-bitly
レゼ.shortlink-cutly
レゼ.shortlink-shorturl
レゼ.speed
レゼ.sticker-attp
レゼ.sticker-attp2
レゼ.sticker-colong
レゼ.sticker-getexif
レゼ.sticker-nyimak
レゼ.sticker-ok
レゼ.sticker-randompatrick
レゼ.sticker-search
レゼ.sticker-slap
レゼ.sticker-smeme
レゼ.sticker-sticker
レゼ.sticker-stickerLLT
レゼ.sticker-toimg
レゼ.sticker-tovideo
レゼ.sticker-ttp
レゼ.sticker-wm
レゼ.store-addlist
レゼ.store-dellist
レゼ.store-list
レゼ.storyanime
レゼ.suit
レゼ.suitpvp
レゼ.suitpvp_ans
レゼ.tes123
レゼ.tool-akungratis
レゼ.tool-alay
レゼ.tool-apkinfo
レゼ.tool-base64
レゼ.tool-calc
レゼ.tool-cek
レゼ.tool-cekapi
レゼ.tool-cekresolution
レゼ.tool-delete
レゼ.tool-encdec
レゼ.tool-getcaption
レゼ.tool-getexif
レゼ.tool-getpp
レゼ.tool-hlh
レゼ.tool-igstalk
レゼ.tool-inspect
レゼ.tool-jadwaltv
レゼ.tool-mention
レゼ.tool-micro
レゼ.tool-modapk
レゼ.tool-npm
レゼ.tool-pesankosong
レゼ.tool-qrcode
レゼ.tool-react
レゼ.tool-readmore
レゼ.tool-readviewonce
レゼ.tool-resize
レゼ.tool-sendquote
レゼ.tool-spamwa
レゼ.tool-styletext
レゼ.tool-timechat
レゼ.tool-toaksara
レゼ.tool-tourl
レゼ.tool-translate
レゼ.tool-weather
レゼ.tool-yuki
レゼ.tqto
レゼ.trainer-pokemon
レゼ.tts
レゼ.videogalau
レゼ.virus-SendVirtex
レゼ.virus-Sendbug
レゼ.virus-list
レゼ.virus-wagb1
レゼ.virus-wagb2
レゼ.virus-waimune1
レゼ.virus-waimune2
レゼ.virus-walist
レゼ.vote-cekvote
レゼ.vote-delete
レゼ.vote-start
レゼ.vote-vote
レゼ.w-cekdosa
レゼ.w-maaf
レゼ.w-unwarn
レゼ.w-warn
レゼ.wangy
レゼ.wikipedia
レゼ.woi
レゼ.xp-profile
レゼ.youtube-play
レゼ.youtube-play2
レゼ.youtube-yta
レゼ.youtube-yts
レゼ.youtube-ytv
レゼ.yuki-bot
レゼ.zodiac
`
const templateButtons = [
    {index: 1, urlButton: {displayText: 'Kenalan sama owner', url: `https://wa.me/6283811034750?text=Hallo admin, saya tertarik untuk menyewa bot ${namebot}`}},
    {index: 4, quickReplyButton: {displayText: 'Owner', id: '.owner'}},
]
let tm = {
text: text,
footer: global.wm,
templateButtons: templateButtons,
image: url
}
conn.sendMessage(m.chat, tm, m)
}
handler.help = ['menu', 'premium']
handler.tags = ['main']
handler.command = /^(menu(help)?|co)$/i

export default handler
